services:
  - type: web
    name: gestionnaire-pharmacie
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://gestionnaire-pharmacie.onrender.com

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: interchange.proxy.rlwy.net
      - key: DB_PORT
        value: 44109
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: lvYxflUFvsKTMRZCRbhwcmmgeCQgVuAx
